### ISSUE TITLE
Prepare Stacklss 3.5

### ISSUE THREAD

**Issue by ghost** [stackless-dev/stackless#112]
Originally reported by: **Anselm Kruis (Bitbucket: [akruis](https://bitbucket.org/akruis), GitHub: [akruis](https://github.com/akruis))**

----------------------------------------

Python 3.5 adds a few new features, which affect Stackless. Here are the results of a quick and dirty review of [What’s New In Python 3.5](https://docs.python.org/3.5/whatsnew/3.5.html):

1. https://bugs.python.org/issue21205: New generator attribute \_\_qualname\_\_. PyGenObject gets two new members: gi_name and gi_qualname.

    Pickling support implemented: a8f3bfa783a9

2. https://bugs.python.org/issue19235: new RecursionError exception

3. https://bugs.python.org/issue24400: PEP 492 - Coroutines with async and await syntax

    As part of the PEP 492 implementation, the tp_reserved slot of PyTypeObject was replaced with a tp_as_async slot. Refer to Coroutine Objects for new types, structures and functions.

    The coroutine type is just a variant of the generator type. Therefore it is possible to reuse the pickling code for generators to enable pickling of coroutines. Implemented with commit e2bf67837ac2.

4. [Argument Clinic](https://docs.python.org/3.5/howto/clinic.html)

----------------------------------------
- Bitbucket: https://bitbucket.org/stackless-dev/stackless/issue/112

**Comment by akruis** [comment]
A very last step: adapt the msi installer. Since Python 3.5 a new Wix based installer is used. Fortunately it is not too hard to adapt the installer.

**Comment by akruis** [comment]
Installers for Windows v3.5.4 are available for download on stackless.com. I can't build macOS installers.
