### ISSUE TITLE
mercurial / git / github

### ISSUE THREAD

**Issue by ghost** [stackless-dev/stackless#118]
Originally reported by: **Kristján Valur Jónsson (Bitbucket: [krisvale](https://bitbucket.org/krisvale), GitHub: [kristjanvalur](https://github.com/kristjanvalur))**

----------------------------------------

Now that python has moved to github,
how do we merge stuff

(couldn't figure out how to start a simple chat, without opening an issue)

----------------------------------------
- Bitbucket: https://bitbucket.org/stackless-dev/stackless/issue/118

**Comment by akruis** [comment]
I just migrated the issues. The only thing left on bitbucket is the wiki.

**Comment by akruis** [comment]
Another finding: I had to modify 3.4-slp Tools/msi/msi.py to create msi installers for v3.4.7-slp.

**Comment by akruis** [comment]
Finally the wiki is on github too. Therefore I close this issue.
