### ISSUE TITLE
release Stackless 2.7.13

### ISSUE THREAD

**Issue by ghost** [stackless-dev/stackless#124]
Originally reported by: **Anselm Kruis (Bitbucket: [akruis](https://bitbucket.org/akruis), GitHub: [akruis](https://github.com/akruis))**

----------------------------------------

Release Stackless 2.7.13. Complete the release check list from https://bitbucket.org/stackless-dev/stackless/wiki/ReleaseProcess:

I propose to base the v2.7.13-slp on commit a5669862ecb8

----------------------------------------
- Bitbucket: https://bitbucket.org/stackless-dev/stackless/issue/124

**Comment by akruis** [comment]
hey, we already have v2.7.14-slp.
