### ISSUE TITLE
Wiki Port

### ISSUE THREAD

**Issue by nyov** [stackless-dev/stackless#148]
I noticed you are interested in a "port" of the bitbucket wiki contents.
Since it only took 10 minutes to clone it from hg and push it to git, here you are:

```
git clone https://github.com/nyov/stackless.wiki.git
cd stackless.wiki/
git remote set-url origin https://github.com/stackless-dev/stackless.wiki.git
git push --force origin
```
(Using `git clone --mirror` option should not be necessary.)

Should then be available under https://github.com/stackless-dev/stackless/wiki
All that would remain is changing the redirect for http://www.stackless.com/

HTH

**Comment by nyov** [comment]
Feel free to let me know if you're not interested in pulling this, so I can nuke my GH fork and recycle some bits ;)  
(Since the magic `.wiki.git` repo kinda requires having one.)

Thanks!

**Comment by kristjanvalur** [comment]
Ah, thanks for the reminder. If you can keep this up for a few days I'll
have a look. Thanks.

**Comment by nyov** [comment]
Certainly, not a problem. I merely wanted to exclude the possibility of it being silently declined.

But if you have a git-mercurial adapter, this can be repeated with a simple
`git clone hg::https://bitbucket.org/stackless-dev/stackless/wiki` (and push to the wiki.git url).
I made no changes, only verified the markup seems nicely compatible with the github wiki.

**Comment by kristjanvalur** [comment]
Thanks, I've cloned it will upload it in time.  Cheers!

2018-01-25 21:34 GMT+00:00 nyov <notifications@github.com>:

**Comment by nyov** [comment]
Awesome. I just noticed I initially forgot to link the actual wiki "preview". I assumed it was self-evident.
Thats how it looks on github:
https://github.com/nyov/stackless/wiki

**Comment by akruis** [comment]
Many thanks for the preparation of the wiki pages. I just uploaded the content and changed the redirect to github.com.
