### ISSUE TITLE
pyenv install stackless-2.7.5 error！

### ISSUE THREAD

**Issue by emaste-r** [stackless-dev/stackless#155]
```
(venv) ➜  1.0.10 pyenv install stackless-2.7.5
Downloading stackless-275-export.tar.bz2...
-> https://www.stackless.com/binaries/stackless-275-export.tar.bz2
error: failed to download stackless-275-export.tar.bz2

BUILD FAILED (OS X 10.13.1 using python-build 20160602)

(venv) ➜  1.0.10 
```
failed to download by:
```
https://www.stackless.com/binaries/stackless-275-export.tar.bz2
```
success by: 
```
http://www.stackless.com/binaries/stackless-275-export.tar.bz2
```

**Comment by akruis** [comment]
1. Stackless version 2.7.5 is completely outdated and has a lot of bugs. Please use a current version.
2. www.stackless.com only supports https. This is probably a bit outdated, but it is not a Stackless bug.

@ctismer: What about a https://letsencrypt.org/ certificate for stackless.com?
