### ISSUE TITLE
MSI Installer deletes other python installations.

### ISSUE THREAD

**Issue by kdschlosser** [stackless-dev/stackless#164]
Stackless 2.7.15 Windows MSI removed a python installation that was in a completely different folder then where Stackless was being installed into. No notification that it was going to remove anything from my computer I am quite upset by the fact that this installer went and deleted data on my machine without my express permission. It deleted a bunch of files that i spent a very long time working on. 

You have no idea how really mad i am that this was released as being OK to do. How can an installer just go and delete other programs???.  WITHOUT ASKING PERMISSION!!!!

There are simply no words to describe my anger. Your software took from me 1 of the 2 things in life that can never be replaced.. MY TIME. 

This other python installation was in a completely different folder. No notification stating it was doing some kind of an upgrade. no notice about it uninstalling the other version. no notice that it was going to remove the other version. It went and deleted it without the use of the uninstaller for that version. I have a dead installation listed in Programs and Features.

**Comment by akruis** [comment]
Hello Kevin, I' very sorry that you have lost a lot of time.

I just looked at the source in Tools/msi/msi.py. Indeed, the Stackless installer uses the same upgrade-code (that's a UUID) as the regular installer since ever. As a consequence Windows considers a Stackless Python msi package to be a legitimate update for a regular Python msi package, which is correct from a pure technical point of view. That explains the observed behaviour.

I don't know why Stackless uses the same upgrade-code. Probably, because it is hard coded into Tools/msi/msi.py and nobody ever changed it. At the moment I don't know how to fix this problem, without breaking the upgrade from already released versions of Stackless to a newer version.

Fortunately Stackless versions >= 3.5 do not have this problem.

**Comment by kdschlosser** [comment]
please for the sake of the sanity of someone else encountering this. put some kind of a warning on the binaries page. and also if possible in the installer. 

What seems strange is that it does not invoke the uninstaller of the other python version. it simply deletes the files. in my specific case i altered some of the std lib files and apparently whatever mechanism that is in place iterates over the file/folder structure and deletes files based on name and not based on some kind of a CRC check to see if the file has been modified. 


This is a very very bad thing. But what makes it worse is it also leaves an orphaned python installation. so windows thinks it's installed when it actually is not. Now if windows works the way it should (HA HA HA good luck there) it should remove the orphaned installation if you try to uninstall it. This is not something that is not 100% guaranteed to work. if it doesn't some registry manipulation or a microsoft FixIt utility located at 

https://support.microsoft.com/en-us/help/17588/fix-problems-that-block-programs-from-being-installed-or-removed

is what is going to need to be done to remove the orphaned installation of python.

I will almost guarantee that the uninstaller for standard/stackless has the CRC flag set. this would do a CRC check on the installed file and not delete it if the file has been modified. But seeing as how the uninstaller is not used i guess the point is moot. 

i do not know as to why even the upgrade-core of standard python does not invoke the uninstaller and it just deletes files. and not a single registry key that was created by the installation of standard python was removed by the stackless installer either. so in my IDE it still lists that python installation as existing when it really does not.

i think the best way to handle this would be to generate a unique application GUID for stackless instead of using the one that is attached to standard python. and the upgrade core would work fine if upgrading a stackless python installation that uses this new GUID. and for the installations that do not, some querying of the registry is going to have to take place to locate Python installations and then simply check the install path for includes/stackless. this would suffice in identifying if it is a stackless installation or not. and have the upgrade-core call the uninstaller for that installation. I do not know how the msi installer for stackless is compiled. so i cannot give an exact example of how to go about changing these things. if it can even be done using an msi installer.

Maybe a shift from providing msi files to installation executables using innosetup or nsis to create the tinstaller. innosetup/nsis provide the same functionality as all of the msi CLI switches so there would be no loss there. 

You would have the ability to do these kinds of checks using innosetup/nsis, and they are very simple utilities. you can even wrap the msi installer into an executable installer that can perform the "dirty" work ahead of time and call the msi installer using 

if doing a full install
/quiet /passive /norestart 

if doing a selective install
/quiet /norestart  /package Package.msi|ProductCode

and to uninstalll 
/uninstall /passive / norestart

there are several possibilities. there for a solution.

the installer cannot destroy data without the users express permission. 

I do have a question. what is the reasoning behind placing the python(version).dll file into the syswow64 or system 32 folder. all it does is booger up other python installations of the same version. It can be placed into the root folder for the stackless installation because the interpreter is in the same folder everything works as advertised. and there is never a worry about a standard python installation loading the stackless compiled dll. It also removes the need to specify a user if you want to install standard and stackless of the same version. 


also the author(s) of stackless can gain a better audience from the standard python author(s). I would strongly suggest letting them know of this bug, if it does exist in their installer.

**Comment by akruis** [comment]
The Stackless installer works as designed, because Stackless is a drop in replacement for C-Python. Therefore it has to use the same registry keys as C-Python and therefore Stackless- and C-Python can't be installed at the same time.

According to PEP 373 we will see two or three more releases of Python 2.7. Active versions of Stackless Python 3 are not affected by this issue. Therefore I won't change the installer, but I added a warning to the download page.

**Comment by kdschlosser** [comment]
no way to make it launch the uninstaller for the existing python that is installed that is in conflict??

The reason I ask this is because the uninstall process does a CRC check to see if the file should be removed. currently the installer grabs the installation directory and deletes the files without caring if the file has been modified. This deletes the users data if a file has been altered for one. But it also leaves an orphaned installation in windows, which is not a great thing to do either.

Launching the uninstaller of the old version should not be all that difficult to do. 

I think that if I install stackless first. then move the python27.dll from the syswow folder into the root of the stackless installation directory and then install python 2.7 and then move the python27.dll once again into the installations folder. both versions can exist on the same machine.

I have done this and have never had any kind of a problem. so i really do not know what registry keys would be shared. This is why i was so taken back when I installed a newer version of stackless. Because i had a c-python installation. and then a stackless installation But the installer went after the c-python installation and not the stackless one. probably because of the installation order. Here is another question that should be answered as well. after i installed stackless and moved the dll. then i ran the installer for c-python how come the c-python installer did not remove the stackless installation??

I am not sure if the stackless installer is the same as the c-python one. and if it is then their installer is also flawed and has the possibility of deleting files. But at the very least if the target directory is not the same. the new installer should simply hijack the registry keys and leave the existing installation alone. if it is the same target folder then it should whatever it needs to do. 

Just a suggestion. I know that python 2.x is EOL, however people will still use it for some years after. 
and deleting a users data without their knowledge is very very wrong. I mean how often do you read a whole website that has a piece of software you want to download?? It is a debockle you do not want to get into with anyone else. It happens that you fixed stackless for me in another issue which caused my need for the code that got deleted to be obsolete. But if this happens with someone else and the code cannot be replaced. I would much rather you not have to deal with that, I would assume that you do not want to have to either. It still makes you feel bad, even if there is a notice/warning on the website. 

Just think if it happened to you and how would you feel about it even if there was a warning on the website that you didn't happen to see???

it is up to you.

"If life wasn't full of adversity it would be boring.." ---Kevin
