### ISSUE TITLE
Make Stackless compatible with subinterpreters

### ISSUE THREAD

**Issue by akruis** [stackless-dev/stackless#186]
Commit 7f8bfc9b9a8 adds a test module for subinterpreters. After preliminary resolving a name collision (issue #185, commit 855d4c1b8383d04) it turned out that the newly added subinterpreter test crashed Stackless.

### Analysis

When Python creates a new interpreter, it creates a new thread state too. Then it initializes the new interpreter and executes modules from the (frozen) importlib. As a consequence the Stackless specific additions to the thread state: st.initial_tstate, st.initial_stub, st.cstack_base, st.cstack_root are already initialized. 

Now, if you used the new interpreter in another thread,  st.cstack_base has a completely wrong value and memory corruption occurs.

**Comment by kristjanvalur** [comment]
Hm, using stackless features in sub-interpreters on different threads
really is a can of worms, getting it to work with multiple threads in the
first place was hard enough.
But it probably shouldn't crash when just using vanilla python :(

mán., 19. nóv. 2018 kl. 07:04 skrifaði Anselm Kruis <
notifications@github.com>:

**Comment by akruis** [comment]
I don't want to add test cases for Stackless stitching in sub-interpreters, but the C-Python test case must not crash.

Fortunately, it was not that difficult, because I already had moved per interpreter state to the appropriate structure (issue #152, commit 0727a8ec807).  Therefore the only remaining challenge was to "reset" the thread-state as soon as all C-stacks have been run.

**Comment by akruis** [comment]
Oops, I found another small problem related to subinterpreter support: slp_register_execute() must be idempotent. Fixed by commit a04e18c.
