### ISSUE TITLE
question about releases.

### ISSUE THREAD

**Issue by kdschlosser** [stackless-dev/stackless#189]
are you going to be providing binaries for python 2.7 builds?

Please say yes you are... I do not want to have to change our build code to also build stackless.

**Comment by akruis** [comment]
You know our download page? https://github.com/stackless-dev/stackless/wiki/Download
The current 2.7 release is Stackless 2.7.15. The next 2.7 release will be Stackless 2.7.16. I expect it to be available in spring 2019.

**Comment by kdschlosser** [comment]
ok because I see that the fix for Cython has been added to v2.7.15-slp
does that mean it is in the binary for 2.7.15??? or is that slated for 2.7.16?

**Comment by akruis** [comment]
The fix has been added to the branch 2.7-slp. This branch contains C-Python 2.7.15 and the Stackless patch. Once C-Python 2.7.16 is released, I’ll merge it into this branch, create Stackless 2.7.16 and build a new installer.

Unfortunately I'm very busy at the moment and I can't build an updated installer now.

**Comment by akruis** [comment]
Stackless 2.7.16 is available for download.
