### ISSUE TITLE
libcryto_1_1x64.dll cannot be installed because the file cannot be found in

### ISSUE THREAD

**Issue by RussiaVk** [stackless-dev/stackless#214]
There is an  error when install  3.7.3 on windows10x64

https://wx2.sinaimg.cn/mw690/00707GTely1g24wyz0w1qj30d3056mx2.jpg
https://wx2.sinaimg.cn/mw690/00707GTely1g24wyz5d50j30im0bddhh.jpg

**Comment by akruis** [comment]
@RussiaVk : Sorry, I'm out of office for a few days and I can't reproduce the problem with my laptop.

Please try to install the Visual Studio 2017 Runtime from https://aka.ms/vs/15/release/vc_redist.x64.exe and retry the installation of Stackless Python.
