### ISSUE TITLE
Unable to compile stackless 3.7.3 in termux: Fatal: you must define __ANDROID_API__

### ISSUE THREAD

**Issue by RussiaVk** [stackless-dev/stackless#215]
I'm trying to compile stackless 3.7.3 in termux (for no particular reason) and keep running into an error running ./configure,

`Fatal: you must define ANDROID_API`

Where do I go about doing this? Got round it by editing the configure script but surly there's a better way?

**Comment by akruis** [comment]
Please make sure you can build regular C-Python. Your problem is most likely not related to Stackless-Python. 

Once you can build C-Python, you should be able to configure Stackless Python. The difference between the "configure"-scripts is minimal.
