### ISSUE TITLE
StacklessLib Repo?

### ISSUE THREAD

**Issue by celestialorb** [stackless-dev/stackless#216]
Apologies for opening an issue on this repo, but is there a repo for stacklesslib? I'd like to open an issue with it.

**Comment by kristjanvalur** [comment]
There is, but it hasn't seen any work for a long time.  Here:  https://bitbucket.org/krisvale/stacklesslib/src/default/
It is subversion, I'm afraid.

**Comment by celestialorb** [comment]
Was there ever any serious work to port it to Python3? I'm seeing references of `2to3` in a few commit messages.
