### ISSUE TITLE
[compile request] Stackless upon Python 3.4.10 (legacy)

### ISSUE THREAD

**Issue by TAbdiukov** [stackless-dev/stackless#223]
Python 3.4.10 happens to be the last legacy version of Python, i.e. last Python3 to support Vista, Server 2003 etc. This version only exists in the form of source code right now, and having a compiled installer would be beneficial for both this project and potential audience. Can I request that version to get compiled? Thanks

**Comment by akruis** [comment]
Sorry, but Stackless 3.4.10 is a source only release and I don't have a VS2010 installation available any longer. Additionally it contains serious bugs.

You can get a copy of VisualStudio 2010 from Microsoft and build the installer yourself.
