### ISSUE TITLE
Testsuite ref leak caused by a new upstream refleak (bpo-37788)

### ISSUE THREAD

**Issue by akruis** [stackless-dev/stackless#226]
The new bug bpo-37788 causes a ref leak in Stackless/unittests/test_channel.py.
As a workaround I can modify the failing test (join the created thread, see bpo-37788).

**Comment by kristjanvalur** [comment]
I´ll add a comment to https://bugs.python.org/issue36402 pointing out 37788

**Comment by akruis** [comment]
Fixed in master-slp and 3.7-slp.
