### ISSUE TITLE
Add support for PEP 567 context variables to tasklets

### ISSUE THREAD

**Issue by akruis** [stackless-dev/stackless#239]
Python 3.7 added the context variables and the module _contextvars_. See [PEP 567](https://www.python.org/dev/peps/pep-0567) for details.

Using tasklets it is possible to decorate a plain old callable as a coroutine (and vice versa). To make such a coroutine fully compatible with C-Python asyncio tasklets should support PEP 567 context variables. In C-Python the _current context_ is a property of the thread state, that is, each thread has its own _current context_. In Stackless Python a thread can have multiple tasklets. Therefore the _current context_ must become a property of the tasklet. 

 I'm still elaborating details.

**Comment by kristjanvalur** [comment]
+1

sun., 18. apr. 2021 kl. 20:02 skrifaði Anselm Kruis <
***@***.***>:

**Comment by akruis** [comment]
First usable code is in https://github.com/akruis/cpython/tree/slp37 (a71d969f06). It is still work in progress.
And here is the project, that needs the contextvar support https://github.com/akruis/slp_coroutines. This project is also work in progress.

**Comment by akruis** [comment]
Implemented in 3.7-slp

**Comment by akruis** [comment]
Merged into main-slp.
