### ISSUE TITLE
extend ceval lltrace output to show stack unwinding operations

### ISSUE THREAD

**Issue by akruis** [stackless-dev/stackless#255]
Currently it is difficult to follow the lltrace output, because it does not show unwinding operations performed by the maco HANDLE_UNWINDING.

Therefore I'll try to add lltrace output to HANDLE_UNWINDING and other appropriate places.

**Comment by akruis** [comment]
Done

**Comment by kristjanvalur** [comment]
Is this a Stackless only issue, or does Cpython also unwind the same (I forget)
