### ISSUE TITLE
Fix a warning in _testcapimodule.c

### ISSUE THREAD

**Issue by akruis** [stackless-dev/stackless#260]
There is a missing cast in _testcapimodule.c line 5061 
```
{"bad_get", bad_get, METH_FASTCALL},
```
causes the following warning:
```
incompatible pointer types initializing 'PyCFunction' (aka 'struct _object *(*)(struct _object *, struct _object *)') with an expression of type 'PyObject *(PyObject *, PyObject *const *, Py_ssize_t)' (aka 'struct _object *(struct _object *, struct _object *const *, long)') [-Wincompatible-pointer-types]
```

Comparison with code from upstream C-Python shows, that a cast `(PyCFunction)` is missing.

**Comment by akruis** [comment]
Invalid: _testcapimodule.c is not a Stackless source, this warning must be fixed upstream.

**Comment by kristjanvalur** [comment]
Is there a corresponding defect upstream?
