### ISSUE TITLE
Dead link in Stackless Wiki (Documentation).

### ISSUE THREAD

**Issue by xcodz-dot** [stackless-dev/stackless#280]
There is a page that leads to examples and the link follows up to bitbucket but bitbucket show 404 error. 

https://github.com/stackless-dev/stackless/wiki#further-reading-material

further reading material -> [Examples](https://bitbucket.org/stackless-dev/stacklessexamples/overview)

**Comment by akruis** [comment]
Many thanks for the report.

A backup of the examples repo is available at https://bitbucket-archive.softwareheritage.org/projects/st/stackless-dev/stacklessexamples.html

**Comment by akruis** [comment]
I converted the stacklessexamples repo to git. It is now available under https://github.com/stackless-dev/stacklessexamples.
And I fixed the broken link.
