### ISSUE TITLE
can someone help with debugging stackless python in visual studio?

### ISSUE THREAD

**Issue by ghost** [stackless-dev/stackless#76]
Originally reported by: **Anonymous**

----------------------------------------

I am using Python Tool for Visual Studio to develop app on stackless however I was not able to debug it and the author of the plug in said 'can't monkeypatch stackless.tasklet.settrace and stackless.tasklet.__call__ anymore', could someone here try to help? below is the link. much appreciated!

http://pytools.codeplex.com/workitem/3003

----------------------------------------
- Bitbucket: https://bitbucket.org/stackless-dev/stackless/issue/76

**Comment by kdschlosser** [comment]
This is 2 different things.. one being the overriding and the other is how to debug stackless python using visual studio. I think.. or is it that you are trying to use an IDE's coding help? if it is the latter. then Python for Visual Studio is pretty handicapped in that area. and you may consider using PyCharm. On the other hand if you are writing C Code as an extension dll for pyhton then I would use Visual Studio. If you are looking to do "Real stack traces and debugging" then you would need to compile a debugging version of stackless python. including debugging builds of all extension dll's (pyd files) used for every library that you want to add to stackless. It is pretty involved to set up a complete debugginig environment. Then you also need to know how to read the stack information and the machine code (if no pdb file is found for a specific dll). I am far from an expert on how to do this as I am also new to creating debugging builds of python/stackless. Maybe someone can chime in if i am incorrect.

Also what are you trying to accomplish by monkey patching that cannot be done by sub classing?

**Comment by akruis** [comment]
This old issue is probably obsolete. In case anybody needs a debugger for Stackless I can recommend [pydevd](https://github.com/fabioz/PyDev.Debugger/) . It is used by various IDEs and supports Stackless quite well.
